### ISSUE TITLE
Examples on openlayers.org are broken

### ISSUE THREAD

**Issue by sbowler** [openlayers/ol-cesium#1014]
Is it just me or do none of the examples on https://openlayers.org/ol-cesium/examples/ seem to work using Google Chrome 110?

I get two errors.

`Uncaught Error: importScripts failed for Workers/createVerticesFromQuantizedTerrainMesh at https://openlayers.org/ol-cesium/node_modules/cesium/Build/Cesium/Workers/createVerticesFromQuantizedTerrainMesh.js   cesiumWorkerBootstrapper.js:30 `

`Uncaught TypeError: Cannot read properties of undefined (reading 'baseUrl')   cesiumWorkerBootstrapper.js:26 `

The code in question appears to be 
```
self.onmessage = function(r) {
  var a = r.data;
  require(a.loaderConfig, [a.workerModule], function(c) {
    self.onmessage = c,
    CESIUM_BASE_URL = a.loaderConfig.baseUrl
  })
}
```

**Comment by lizhao520q** [comment]
Is there any solution?

**Comment by matthias-ccri** [comment]
It looks like a corrupted deployment. The [customProj](https://openlayers.org/ol-cesium/examples/customProj.html) page gets a 404 on a request to this asset: `https://openlayers.org/ol-cesium/node_modules/cesium/Build/Cesium/Workers/_commonjsHelpers-89c9b271.js`

**Comment by matthias-ccri** [comment]
@mike-web-dev what do you mean by "it works up to version ...". Is the [web site](https://openlayers.org/ol-cesium/examples/) versioned?

**Comment by mike-web-dev** [comment]
testing locally the example files work with cesium 1.100.0, using cesium 1.101.0 or above return a

```
Uncaught Error: importScripts failed for Workers/createVerticesFromQuantizedTerrainMesh at http://10.10.30.82:3000/node_modules/cesium/Build/Cesium/Workers/createVerticesFromQuantizedTerrainMesh.js
http://requirejs.org/docs/errors.html#importscripts
Error: Uncaught Error: importScripts failed for Workers/createVerticesFromQuantizedTerrainMesh at http://10.10.30.82:3000/node_modules/cesium/Build/Cesium/Workers/createVerticesFromQuantizedTerrainMesh.js
http://requirejs.org/docs/errors.html#importscripts  at http://10.10.30.82:3000/commons.js:16381:58
```

**Comment by matthias-ccri** [comment]
@mike-web-dev hm, I just pulled commit b03f4f7 from ol-cesium, ran `npm install` and `make serve` and all the examples **work on my machine**.

Whenever there's a "works on my machine" situation, it's probably the case that the missing lockfile (package-lock.json) is to blame. If this project had a lockfile, our builds would be identical, but since it does not, we may have different node_modules dependencies. See https://github.com/openlayers/ol-cesium/issues/962

@mike-web-dev before you fix your setup by deleting node_modules, can you help us know what your node_modules contains, so we can figure out the root of this issue? See below.

The only way to do this is with a lockfile. Please delete the `.npmrc` which says `package-lock=false`, and run `npm install` again, which should generate a lockfile. Please make a copy of that file.

Then delete the `package-lock.json` AND `node_modules`, and run `npm install` again. Now you should have two different lockfiles, and now we can see which dependencies changed between the failing build and the passing build.

What's the best way for you to send us both versions of the lockfiles? Pasting both into this GitHub Issue? or using Gists?

@gberaudo this is an example of why this repo needs to have its lockfile tracked. Please see my comment on  https://github.com/openlayers/ol-cesium/issues/962 and please reopen that ticket for tracking.

**Comment by mike-web-dev** [comment]
@matthias-ccri there was no difference in the package-lock.json files, it looks to be a caching issue. Running the 2.13.2 and it seems to be working now

**Comment by fredj** [comment]
See #1040

**Comment by gberaudo** [comment]
Hi, thanks for the discussions and work on fixing the issue.
You are right @matthias-ccri , lock files has improved enough so that we should use it now.
