### ISSUE TITLE
3D models synced with open layers?

### ISSUE THREAD

**Issue by thinkpadder1** [openlayers/ol-cesium#211]
I saw #163 . What I'm trying to do:
1. Make a feature, like a point, in Openlayers.
2. Set a key value pair with ol.Feature.set('model', '/models/airplane.gltf'). Maybe with some basic options like minimumPixelSize and scale.
3. When switching from Openlayers to Cesium, it replaces the point with that model.

Is something like having a 3D model synced (i.e. position) with a point in Openlayers possible? If so, can I please get an example? Thank you.

**Comment by gberaudo** [comment]
It is possible to implement it:
- either in ol3-cesium, by adding this case in the
  `olcs.FeatureConverter.prototype.olPointGeometryToCesium() method`;
- or in your application, by subclassing the `olcs.FeatureConverter` and
  overriding the above method.

I think it is acceptable to add an experimental implementation in Ol3-Cesium
(solution 1). It would simply use the Cesium Model option hash described
in https://cesiumjs.org/Cesium/Build/Documentation/Model.html instead of
the gltf url, like you propose.

There is no example of it yet, but Pull Requests are welcomed.
Please let me know if you want to work on this.

**Comment by thinkpadder1** [comment]
I ended up kind of hacking this...

I added a toggle button to switch between OL and Cesium. Using [olcs.OLCesium.getEnabled()](http://openlayers.org/ol3-cesium/apidoc/olcs.OLCesium.html#getEnabled), I would apply a style that would hide/show the features with a model.

The cool thing about OL is that you can store a reference to the model from Cesium directly in the feature by using the [ol.Feature.set(key, value)](http://openlayers.org/en/v3.8.2/apidoc/ol.Feature.html#set) function. So, when I delete any feature, I call the Cesium function destroy() on the model, I can move it etc.

The above combined with [forEachFeature](http://openlayers.org/en/v3.8.2/apidoc/ol.source.Vector.html#forEachFeature) solved the problem for me.

**Comment by gberaudo** [comment]
Thank you @thinkpadder1 for the tip.
The issue is still valid in my opinion, so we can keep it opened.

**Comment by malvandi** [comment]
@thinkpadder1 you mean, we must add models and hide features in globe and remove models and shoe features in 2D view?
