### ISSUE TITLE
Version 3.9.4 (latest) won't install from npm

### ISSUE THREAD

**Issue by metazool** [openlayers/ol-cesium#378]
The latest version of ol3-cesium won't install from npm.

$ npm install ol3-cesium
npm ERR! cb() never called!

However if I explicitly spell out a previous version it works all right: 

$ npm install ol3-cesium@3.9.2
└─┬ ol3-cesium@3.9.2 
  ├── async@0.2.10 
  └─┬ htmlparser2@3.7.3 
    ├── domelementtype@1.3.0 
    ├── domhandler@2.2.1 
    ├─┬ domutils@1.5.1 
    │ └─┬ dom-serializer@0.1.0 
    │   ├── domelementtype@1.1.3 
    │   └── entities@1.1.1 
    ├── entities@1.0.0 
    └─┬ readable-stream@1.1.14 
      ├── core-util-is@1.0.2 
      ├── inherits@2.0.1 
      ├── isarray@0.0.1 
      └── string_decoder@0.10.31

**Comment by gberaudo** [comment]
Thanks for reporting the issue.

I did not know the OL3-Cesium package was pushed to the npm repository.
Maybe @bartvde knows better about this.

@bartvde, could you please look at this?
The latest OL3-cesium version is 1.18. How is calculated the version number found on npm

**Comment by bartvde** [comment]
This was basically a temporary solution until we got official npm packages set up for ol3-cesium, I generated it from: https://github.com/bartvde/ol3-cesium/commits/npm

This is not up to date with the latest ol3-cesium, mostly because in recent versions it's compiled together with ol3 which is not usable for my situation. I've only done cherry-picking of some issues that were blocking my specific application.

How I came to the version number I don't recall.

I should probably rename ol3-cesium on npm to something else to make it clear it's not an official ol3-cesium package?

As for the specific issue, for me it's working ok. What node / npm version are you using @metazool ?

```
Barts-MacBook-Air:tmp bartvandeneijnden$ npm install ol3-cesium
/private/tmp
└─┬ ol3-cesium@3.9.4 
  ├── async@0.2.10 
  └─┬ htmlparser2@3.7.3 
    ├── domelementtype@1.3.0 
    ├── domhandler@2.2.1 
    ├─┬ domutils@1.5.1 
    │ └─┬ dom-serializer@0.1.0 
    │   ├── domelementtype@1.1.3 
    │   └── entities@1.1.1 
    ├── entities@1.0.0 
    └─┬ readable-stream@1.1.14 
      ├── core-util-is@1.0.2 
      ├── inherits@2.0.1 
      ├── isarray@0.0.1 
      └── string_decoder@0.10.31 

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
```

**Comment by gberaudo** [comment]
Thanks for the clarifications @bartvde.
It would be great to have the official OL3-Cesium version pushed on npm every month as part of the official release. Is it as easy as calling `npm publish` or there is something else to do?

**Comment by bartvde** [comment]
No we need to add an UmdWrapper as well to build.js similar to ol3

**Comment by gberaudo** [comment]
@bartvde, that would be awesome, if you could contribute your wrapper to OL3-Cesium.

**Comment by gberaudo** [comment]
The most important is that people specifying `ol3-cesium` in their `package.json` actually get the latest stable release from the project.

@bartvde, could you please add me as an owner of the package?
```
npm owner add gberaudo ol3-cesium
```

If possible, it would also be great if you could publish the current stable version: it is 1.20.0 from today.
Then I guess you/I will need to unpublish all 3.x versions so that version 1.20.0 is picked up on `npm install`.

Thanks @bartvde. Looking forward to having the publication to npm as part of the monthly release process.

**Comment by bartvde** [comment]
I added you as an owner @gberaudo 
Not sure when I have time for this though.
I'm going to rename my old package to a different name, not ol3-cesium.

**Comment by gberaudo** [comment]
OK, thanks @bartvde.

**Comment by gberaudo** [comment]
There is now an [ol-cesium](https://www.npmjs.com/package/ol-cesium) package. Please try to use it and come back to use if you have issues.
