### ISSUE TITLE
Openlayers vectorlayer

### ISSUE THREAD

**Issue by DeManHemZelfe** [openlayers/ol-cesium#740]
Hey everyone,

I want to make 3D Buildings in a vectorlayers. I work with typescript, openlayers and OLcesium
This is the source and the layer

`   pandSource = new VectorSource({
    format: new GeoJSON(),
    url: (extent, resolution, projection) => {
      return 'https://cors-anywhere.herokuapp.com/http://godzilla.bk.tudelft.nl:8090/geoserver/BAG3D/wfs?service=WFS&' +
        'version=1.0.0&request=GetFeature&typeName=pand3d&' +
        'outputFormat=json&srsname=EPSG:28992&' +
        'bbox=' + extent.join(',') + ',EPSG:28992';
    },
    strategy: bbox
  });
`

`  pand3DLayer = new VectorLayer({
    minResolution: 0,
    maxResolution: 0.7,
    source: this.pandSource,
    zIndex: 4,
  });`

Does anyone knows how i can make the buildings in 3D?

Regards Niels

**Comment by gberaudo** [comment]
If you are only interested in the footprint of the buildings, you can use the altitudeMode
https://github.com/openlayers/ol-cesium/blob/20bbb7d14d937980e0afdd8b07830ef1e4cc646c/examples/vectors.js#L45

Otherwise there is no support for 3D buildings from 2D features. See https://github.com/openlayers/ol-cesium/issues/360.
